name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential cmake libgtest-dev lcov

    - name: Build GoogleTest
      run: |
        cd /usr/src/gtest
        sudo cmake .
        sudo make
        sudo cp *.a /usr/lib

    - name: Clean old binaries
      run: rm -f tests program.out

    - name: Build main program
      run: make

    - name: Build and run tests
      run: |
        g++ -fprofile-arcs -ftest-coverage -std=c++17 -pthread main.cpp student.cpp test_student.cpp -lgtest -lgtest_main -o tests
        ./tests
