name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential cmake libgtest-dev lcov

    - name: Build GoogleTest
      run: |
        cd /usr/src/googletest
        sudo cmake -S . -B build
        sudo cmake --build build 
        sudo cp build/lib/*.a /usr/lib

    - name: Clean old binaries
      run: rm -f tests program.out

    - name: Build main program
      run: make program.out

    - name: Build and run tests
      run: make tests && ./tests
